# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'week7' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

    pod 'RxSwift', '6.0.0-rc.2'
    pod 'RxCocoa', '6.0.0-rc.2'

  # Pods for week7

end
