# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'rxswiftExercises' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for rxswiftExercises

  target 'rxswiftExercisesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'rxswiftExercisesUITests' do
    # Pods for testing
  end

pod 'RxSwift', '~> 4.0'

end
